# https://linuxconfig.org/install-gui-on-ubuntu-server-18-04-bionic-beaver
---
- hosts: todeploy
  tasks:
  - name: upgrade packages
    become: yes
    apt: upgrade=dist

  - name: update packages
    become: yes
    apt: update_cache=yes
    
  - name: install GUI installer
    become: yes
    apt: name=tasksel state=present
    
  - name: install xfce
    become: yes
    shell: tasksel install xubuntu-core
    
  - name: start display manager
    become: yes
    shell: service lightdm start
