
- hosts: mysql
  tasks:
  - name: update packages
    become: yes
    apt: "update_cache=yes"

  - name: prerequisites and mysql
    become: yes
    apt: name={{item}} state=latest
    with_items:
            - "mysql-server"

  - name: allow remote connections
    become: yes
    lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp="^bind-address" line="bind-address=0.0.0.0"

  - name: load new configuration
    become: yes
    command: /usr/sbin/service mysql restart   

  - name: check service status
    command: /usr/sbin/service mysql status
    changed_when: false

  - name: create database for development
    become: yes
    shell: /usr/bin/mysql -u root -e "create database IF NOT EXISTS devops default character set utf8 default collate utf8_bin"
 
  - name: create user for development
    become: yes
    shell: /usr/bin/mysql -u root -e "GRANT ALL PRIVILEGES ON devops.* to develop@'192.168.1.%' IDENTIFIED BY 'develop'"
