---
- hosts: todeploy
  vars:
   os_user: "tudi"
   
  tasks: 
  - name: decrease swapiness
    become: yes
    lineinfile:
     dest: /etc/sysctl.conf
     line: 'vm.swappiness=5'
     
  - name: entrypoint ramdisk
    become: yes
    file:
       path: /ramcache
       state: directory
       mode: 0766

  - name: ram disk
    become: yes
    lineinfile:
     dest: /etc/fstab
     line: 'tmpfs    /ramcache tmpfs   nodev,nosuid,nodiratime,size=5120M   0 0'
     
  - name: create soft link for ramcache
    become: yes
    file:
     src:  /ramcache
     dest: /home/{{os_user}}/ram
     state: link
