---
- hosts: wordpress
  tasks:
  - name: update packages
    become: yes
    apt: update_cache=yes

  - name: prerequisites
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: prerequisites
    become: yes
    apt: name={{item}} state=present
    with_items:
        - "apache2"
        - "mysql-server"
        - "php7.2-mysql"
        - "php7.2"
        - "libapache2-mod-php7.2"
        - "python-mysqldb"
        - "php7.2-gd"
        - "php7.2-ssh2"
        - "vsftpd"
