---
- hosts: wordpress
  vars:
    wp_mysql_db: "wordpress"
    wp_mysql_user: "wordpress"
    wp_mysql_password: "admin"

  tasks:
    - name: create mysql db
      become: yes
      mysql_db: name={{wp_mysql_db}} state=present

    - name: mysql user
      become: yes
      mysql_user:
        name={{wp_mysql_user}}
        password={{wp_mysql_password}}
        priv=*.*:ALL
   
